/**
 * Mapa českých křestních jmen → 5. pád (oslovení).
 *
 * Používá se pro `{{osloveni}}` template proměnnou v email šablonách
 * (viz lib/actions/formular.ts, lib/actions/akce.ts). Nahrazuje automatické
 * skloňování pravidly — kurátorovaný dictionary lookup s bezpečným fallbackem
 * na původní jméno, pokud není v mapě.
 *
 * Rozšiřitelnost: přidej řádek `jmeno: "Oslovení"`. Klíč musí být lowercase
 * nominativ, value je správný vocativ s kapitalizací.
 */

const VOCATIVE_MAP: Record<string, string> = {
  // Mužská jména
  jan: "Jane",
  petr: "Petře",
  pavel: "Pavle",
  martin: "Martine",
  tomáš: "Tomáši",
  jiří: "Jiří",
  lukáš: "Lukáši",
  david: "Davide",
  jakub: "Jakube",
  marek: "Marku",
  michal: "Michale",
  josef: "Josefe",
  ondřej: "Ondřeji",
  daniel: "Danieli",
  radek: "Radku",
  roman: "Romane",
  filip: "Filipe",
  karel: "Karle",
  dominik: "Dominiku",
  aleš: "Aleši",
  patrik: "Patriku",
  václav: "Václave",
  adam: "Adame",
  stanislav: "Stanislave",
  jaroslav: "Jaroslave",
  matěj: "Matěji",
  vojtěch: "Vojtěchu",
  zdeněk: "Zdeňku",
  miroslav: "Miroslave",
  františek: "Františku",
  štěpán: "Štěpáne",
  radim: "Radime",
  oldřich: "Oldřichu",
  hynek: "Hynku",
  ivo: "Ivo",
  bohumil: "Bohumile",
  igor: "Igore",
  oskar: "Oskare",
  rostislav: "Rostislave",
  emil: "Emile",
  erik: "Eriku",
  richard: "Richarde",
  viktor: "Viktore",
  leo: "Leo",
  oliver: "Olivere",
  samuel: "Samuele",
  sebastián: "Sebastiáne",
  tobiáš: "Tobiáši",
  denis: "Denisi",
  alex: "Alexi",
  kevin: "Kevine",
  robin: "Robine",
  kryštof: "Kryštofe",
  eduard: "Eduarde",
  norbert: "Norberte",
  libor: "Libore",
  dalibor: "Dalibore",
  lumír: "Lumíre",
  bedřich: "Bedřichu",
  leopold: "Leopolde",
  augustin: "Augustine",
  maxim: "Maxime",
  nicolas: "Nicolasi",
  rené: "René",
  otakar: "Otakare",
  prokop: "Prokope",
  boris: "Borisi",
  ctibor: "Ctibore",
  cyril: "Cyrile",
  dušan: "Dušane",
  evžen: "Evžene",
  gustav: "Gustave",
  jindřich: "Jindřichu",
  kamil: "Kamile",
  ladislav: "Ladislave",
  miloslav: "Miloslave",
  oto: "Oto",
  rudolf: "Rudolfe",
  svatopluk: "Svatopluku",
  vilém: "Viléme",
  zbyněk: "Zbyňku",
  alan: "Alane",
  albert: "Alberte",
  alois: "Aloisi",
  andrej: "Andreji",
  antonín: "Antoníne",
  arnošt: "Arnošte",
  benedikt: "Benedikte",
  bohuslav: "Bohuslave",
  bronislav: "Bronislave",
  ctirad: "Ctirade",
  čestmír: "Čestmíre",
  dalimil: "Dalimile",
  dobroslav: "Dobroslave",
  emanuel: "Emanueli",
  ferdinand: "Ferdinande",
  gabriel: "Gabrieli",
  goran: "Gorane",
  hugo: "Hugo",
  ivan: "Ivane",
  ibrahim: "Ibrahime",
  jáchym: "Jáchyme",
  jaromír: "Jaromíre",
  jonáš: "Jonáši",
  julius: "Julie",
  kristián: "Kristiáne",
  leoš: "Leoši",
  luboš: "Luboši",
  milan: "Milane",
  miloš: "Miloši",
  natan: "Natane",
  oleg: "Olegu",
  radovan: "Radovane",
  radoslav: "Radoslave",
  rastislav: "Rastislave",
  robert: "Roberte",
  roland: "Rolande",
  sergej: "Sergeji",
  slavomír: "Slavomíre",
  šimon: "Šimone",
  teodor: "Teodore",
  tibor: "Tibore",
  valentin: "Valentine",
  vladimír: "Vladimíre",
  vratislav: "Vratislave",
  zoltán: "Zoltáne",

  // Ženská jména
  marie: "Marie",
  jana: "Jano",
  eva: "Evo",
  anna: "Anno",
  lenka: "Lenko",
  kateřina: "Kateřino",
  lucie: "Lucie",
  hana: "Hano",
  petra: "Petro",
  veronika: "Veroniko",
  tereza: "Terezo",
  martina: "Martino",
  alena: "Aleno",
  markéta: "Markéto",
  nikola: "Nikolo",
  barbora: "Barboro",
  kristýna: "Kristýno",
  simona: "Simono",
  eliška: "Eliško",
  michaela: "Michaelo",
  monika: "Moniko",
  zuzana: "Zuzano",
  ivana: "Ivano",
  klára: "Kláro",
  andrea: "Andreo",
  denisa: "Deniso",
  karolína: "Karolíno",
  dominika: "Dominiko",
  adéla: "Adélo",
  vendula: "Vendulo",
  radka: "Radko",
  dagmar: "Dagmar",
  blanka: "Blanko",
  gabriela: "Gabrielo",
  ilona: "Ilono",
  irena: "Ireno",
  jitka: "Jitko",
  kamila: "Kamilo",
  leona: "Leono",
  magdalena: "Magdaleno",
  olga: "Olgo",
  pavla: "Pavlo",
  renata: "Renato",
  romana: "Romano",
  sabina: "Sabino",
  šárka: "Šárko",
  věra: "Věro",
  zdeňka: "Zdeňko",
  žaneta: "Žaneto",
  nela: "Nelo",
  natálie: "Natálie",
  vanesa: "Vaneso",
  laura: "Lauro",
  sofie: "Sofie",
  amálie: "Amálie",
  julie: "Julie",
  emilie: "Emilie",
  beáta: "Beáto",
  tamara: "Tamaro",
  valerie: "Valerie",
  ema: "Emo",
  lada: "Lado",
  dana: "Dano",
  helena: "Heleno",
  božena: "Boženo",
  růžena: "Růženo",
  milada: "Milado",
  libuše: "Libuše",
  vlasta: "Vlasto",
  květa: "Květo",
  jaroslava: "Jaroslavo",
  miloslava: "Miloslavo",
  stanislava: "Stanislavo",
  alexandra: "Alexandro",
  anežka: "Anežko",
  běla: "Bělo",
  cecílie: "Cecílie",
  dagmara: "Dagmaro",
  edita: "Edito",
  elena: "Eleno",
  ester: "Ester",
  františka: "Františko",
  gábina: "Gábino",
  hedvika: "Hedviko",
  ida: "Ido",
  iveta: "Iveto",
  jarmila: "Jarmilo",
  jaromíra: "Jaromíro",
  jolana: "Jolano",
  justýna: "Justýno",
  karina: "Karino",
  klaudie: "Klaudie",
  kristina: "Kristino",
  liana: "Liano",
  lilie: "Lilie",
  linda: "Lindo",
  magda: "Magdo",
  mariana: "Mariano",
  milena: "Mileno",
  mirela: "Mirelo",
  naďa: "Naďo",
  nina: "Nino",
  noemi: "Noemi",
  olívie: "Olívie",
  patricie: "Patricie",
  pavlína: "Pavlíno",
  radmila: "Radmilo",
  rebeka: "Rebeko",
  regina: "Regino",
  rita: "Rito",
  sandra: "Sandro",
  silvie: "Silvie",
  soňa: "Soňo",
  taťána: "Taťáno",
  verona: "Verono",
  viktorie: "Viktorie",
  viola: "Violo",
  yvona: "Yvono",
  zina: "Zino",
}

/**
 * Vrátí 5. pád (oslovení) pro dané křestní jméno, nebo bezpečný fallback.
 *
 *  - trim mezer na vstupu
 *  - case-insensitive lookup
 *  - null / undefined / prázdný string → "" (safe default)
 *  - nenalezeno v mapě → vrátí původní trimnuté jméno beze změny
 *
 * Příklady:
 *   getVocativeName("Nikola")  → "Nikolo"
 *   getVocativeName("nikola")  → "Nikolo"
 *   getVocativeName(" PETR ")  → "Petře"
 *   getVocativeName("Amálie")  → "Amálie"
 *   getVocativeName("Maicon")  → "Maicon"
 *   getVocativeName("")        → ""
 *   getVocativeName(null)      → ""
 */
export function getVocativeName(firstName: string | null | undefined): string {
  if (!firstName) return ""
  const trimmed = firstName.trim()
  if (!trimmed) return ""
  return VOCATIVE_MAP[trimmed.toLowerCase()] ?? trimmed
}
